import type { Alert } from '@/types/cyberguard';

export const ATTACK_CATEGORIES = {
  TRADITIONAL: [
    'SSH Brute Force',
    'Ransomware',
    'Port Scanning',
    'DDoS Attack',
    'SQL Injection',
    'Malware Detection',
    'Phishing',
    'Credential Stuffing',
    'Unauthorized Access',
    'Cloud IAM Misconfiguration',
  ],
  AI_SECURITY: [
    'Sensitive Data Leakage',
    'Prompt Injection',
    'Agent Goal Hijacking',
    'Unsafe Tool Invocation',
    'Excessive Agent Permissions',
    'AI Tool Abuse',
    'Model Manipulation',
  ],
} as const;

export const SCENARIO_ALIASES: Record<string, string> = {
  'Tool Abuse': 'AI Tool Abuse',
  'AI Tool Abuse': 'AI Tool Abuse',
  'Model Manipulation': 'Model Manipulation',
  'Prompt Injection': 'Prompt Injection',
  'Sensitive Data Leakage': 'Sensitive Data Leakage',
  'Agent Goal Hijacking': 'Agent Goal Hijacking',
  'Unsafe Tool Invocation': 'Unsafe Tool Invocation',
  'Excessive Agent Permissions': 'Excessive Agent Permissions',
};

export const INCIDENT_SCENARIOS = {
  'SQL Injection': {
    sample_id: 'INC-2026-0607',
    affected_system: 'Payment Application',
    indicator: '203.0.113.121',
    playbook: 'PB-SQL-INJECTION',
    efficacy_score: 0.97,
  },
  Phishing: {
    sample_id: 'INC-2026-0317',
    affected_system: 'Employee Mailbox',
    indicator: '203.0.113.14',
    playbook: 'PB-PHISHING-RESPONSE',
    efficacy_score: 0.91,
  },
  'SSH Brute Force': {
    sample_id: 'INC-2026-0156',
    affected_system: 'Linux Authentication Server',
    indicator: '203.0.113.186',
    playbook: 'PB-SSH-BRUTE-FORCE',
    efficacy_score: 0.94,
  },
  'Unauthorized Access': {
    sample_id: 'INC-2026-0687',
    affected_system: 'Cloud Management Console',
    indicator: '203.0.113.249',
    playbook: 'PB-UNAUTHORIZED-ACCESS',
    efficacy_score: 0.94,
  },
  'Malware Detection': {
    sample_id: 'INC-2026-0492',
    affected_system: 'Employee Workstation',
    indicator: '203.0.113.95',
    playbook: 'PB-MALWARE-CONTAINMENT',
    efficacy_score: 0.92,
  },
  'Port Scanning': {
    sample_id: 'INC-2026-0093',
    affected_system: 'Network Gateway',
    indicator: '203.0.113.121',
    playbook: 'PB-PORT-SCAN',
    efficacy_score: 0.91,
  },
  'Credential Stuffing': {
    sample_id: 'INC-2026-0066',
    affected_system: 'Customer Authentication Portal',
    indicator: '203.0.113.1',
    playbook: 'PB-CREDENTIAL-STUFFING',
    efficacy_score: 0.93,
  },
  'DDoS Attack': {
    sample_id: 'INC-2026-0597',
    affected_system: 'Customer API',
    indicator: '203.0.113.135',
    playbook: 'PB-DDOS',
    efficacy_score: 0.95,
  },
  Ransomware: {
    sample_id: 'INC-2026-0446',
    affected_system: 'Production File Storage',
    indicator: '203.0.113.161',
    playbook: 'PB-RANSOMWARE',
    efficacy_score: 0.96,
  },
  'Cloud IAM Misconfiguration': {
    sample_id: 'INC-2026-0249',
    affected_system: 'Cloud Storage Environment',
    indicator: '203.0.113.207',
    playbook: 'PB-IAM-MISCONFIGURATION',
    efficacy_score: 0.95,
  },
  'Sensitive Data Leakage': {
    sample_id: 'INC-2026-0738',
    affected_system: 'Enterprise AI Assistant',
    indicators: ['AGENT-046', 'PH-5215'],
    playbook: 'PB-AI-DATA-LEAKAGE',
    efficacy_score: 0.94,
  },
  'Prompt Injection': {
    sample_id: 'INC-2026-0817',
    affected_system: 'Customer Support AI Agent',
    indicators: ['AGENT-032', 'PH-1834'],
    playbook: 'PB-PROMPT-INJECTION',
    efficacy_score: 0.93,
  },
  'Agent Goal Hijacking': {
    sample_id: 'INC-2026-0784',
    affected_system: 'Autonomous Research Agent',
    indicators: ['AGENT-046', 'PH-4070'],
    playbook: 'PB-AI-GOAL-HIJACKING',
    efficacy_score: 0.92,
  },
  'Unsafe Tool Invocation': {
    sample_id: 'INC-2026-0847',
    affected_system: 'Enterprise Tool Gateway',
    indicators: ['AGENT-021', 'PH-7505'],
    playbook: 'PB-AI-SAFE-TOOL-INVOCATION',
    efficacy_score: 0.95,
  },
  'Excessive Agent Permissions': {
    sample_id: 'INC-2026-0969',
    affected_system: 'Internal Copilot',
    indicators: ['AGENT-026', 'PH-2330'],
    playbook: 'PB-AI-LEAST-PRIVILEGE',
    efficacy_score: 0.95,
  },
  'AI Tool Abuse': {
    sample_id: 'INC-2026-0859',
    affected_system: 'AI Agent Tool Gateway',
    indicators: ['AGENT-038', 'PH-6320'],
    playbook: 'PB-AI-TOOL-ABUSE',
    efficacy_score: 0.96,
  },
} as const;

export const PRESET_ALERTS: Record<string, Alert> = {
  'SSH Brute Force': {
    incident_id: 'INC-2026-0041',
    category: 'traditional',
    incident_type: 'SSH Brute Force',
    affected_system: 'prod-ssh-gateway-01',
    description: 'Over 500 failed SSH login attempts from an unknown IP subnet within 30 seconds.',
    severity: 'HIGH',
  },
  Ransomware: {
    incident_id: 'INC-2026-0043',
    category: 'traditional',
    incident_type: 'Ransomware',
    affected_system: 'file-share-srv-04',
    description: 'Mass file renaming and rapid encryption patterns detected across shared volumes.',
    severity: 'CRITICAL',
  },
  'Port Scanning': {
    incident_id: 'INC-2026-0044',
    category: 'traditional',
    incident_type: 'Port Scanning',
    affected_system: 'dmz-firewall-01',
    description: 'Sequential TCP probing across ports 1-1024 from a single external host.',
    severity: 'MEDIUM',
  },
  'DDoS Attack': {
    incident_id: 'INC-2026-0045',
    category: 'traditional',
    incident_type: 'DDoS Attack',
    affected_system: 'edge-load-balancer',
    description: 'Volumetric traffic surge is saturating edge routing and degrading service availability.',
    severity: 'CRITICAL',
  },
  'SQL Injection': {
    incident_id: 'INC-2026-0046',
    category: 'traditional',
    incident_type: 'SQL Injection',
    affected_system: 'web-billing-api',
    description: 'A request parameter contains a UNION SELECT payload targeting the billing database.',
    severity: 'HIGH',
  },
  'Malware Detection': {
    incident_id: 'INC-2026-0047',
    category: 'traditional',
    incident_type: 'Malware Detection',
    affected_system: 'endpoint-workstation-88',
    description: 'EDR detected an unverified binary attempting process memory injection.',
    severity: 'HIGH',
  },
  Phishing: {
    incident_id: 'INC-2026-0048',
    category: 'traditional',
    incident_type: 'Phishing',
    affected_system: 'mail-gateway-01',
    description: 'An executive impersonation email includes a suspicious macro-enabled attachment.',
    severity: 'HIGH',
  },
  'Credential Stuffing': {
    incident_id: 'INC-2026-0042',
    category: 'traditional',
    incident_type: 'Credential Stuffing',
    affected_system: 'auth-service-01',
    description: 'Thousands of failed logins are distributed across customer accounts and rotating IP addresses.',
    severity: 'CRITICAL',
  },
  'Unauthorized Access': {
    incident_id: 'INC-2026-0049',
    category: 'traditional',
    incident_type: 'Unauthorized Access',
    affected_system: 'internal-vault-db',
    description: 'An administrative session was established using credentials marked as revoked.',
    severity: 'CRITICAL',
  },
  'Cloud IAM Misconfiguration': {
    incident_id: 'INC-2026-0050',
    category: 'traditional',
    incident_type: 'Cloud IAM Misconfiguration',
    affected_system: 'aws-s3-analytics-bucket',
    description: 'A storage bucket policy was changed to allow public read and write access.',
    severity: 'HIGH',
  },
  'Prompt Injection': {
    incident_id: 'INC-2026-0057',
    category: 'ai_security',
    incident_type: 'Prompt Injection',
    affected_system: 'llm-gateway-prod',
    description: 'Untrusted content attempted to override system instructions and expose protected context.',
    severity: 'HIGH',
  },
  'AI Tool Abuse': {
    incident_id: 'INC-2026-0058',
    category: 'ai_security',
    incident_type: 'AI Tool Abuse',
    affected_system: 'agent-executor-svc',
    description: 'An agent attempted shell operations outside its approved tool scope.',
    severity: 'HIGH',
  },
  'Tool Abuse': {
    incident_id: 'INC-2026-0058',
    category: 'ai_security',
    incident_type: 'Tool Abuse',
    affected_system: 'agent-executor-svc',
    description: 'An agent attempted shell operations outside its approved tool scope.',
    severity: 'HIGH',
  },
  'Excessive Agent Permissions': {
    incident_id: 'INC-2026-0059',
    category: 'ai_security',
    incident_type: 'Excessive Agent Permissions',
    affected_system: 'customer-support-bot',
    description: 'A read-only workflow requested broad write access to customer records.',
    severity: 'HIGH',
  },
  'Sensitive Data Leakage': {
    incident_id: 'INC-2026-0060',
    category: 'ai_security',
    incident_type: 'Sensitive Data Leakage',
    affected_system: 'llm-output-filter',
    description: 'The model response stream contains customer PII and payment data.',
    severity: 'CRITICAL',
  },
  'Model Manipulation': {
    incident_id: 'INC-2026-0061',
    category: 'ai_security',
    incident_type: 'Model Manipulation',
    affected_system: 'rag-embedding-index',
    description: 'Suspicious documents appear to be poisoning retrieval results and model context.',
    severity: 'HIGH',
  },
  'Unsafe Tool Invocation': {
    incident_id: 'INC-2026-0062',
    category: 'ai_security',
    incident_type: 'Unsafe Tool Invocation',
    affected_system: 'code-interpreter-tool',
    description: 'A tool request contains unapproved code and outbound network operations.',
    severity: 'CRITICAL',
  },
  'Agent Goal Hijacking': {
    incident_id: 'INC-2026-0063',
    category: 'ai_security',
    incident_type: 'Agent Goal Hijacking',
    affected_system: 'autonomous-soc-agent',
    description: 'Conversation content redirected an agent from log analysis to unauthorized account creation.',
    severity: 'CRITICAL',
  },
};